//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRemark
    {
        public int RemID { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Remark { get; set; }
        public string Type { get; set; }
        public string FilePath { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
