//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employees
    {
        public int EmpId { get; set; }
        public string Name { get; set; }
        public string fatherName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Aadhaar { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
