//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TallyData
    {
        public int TallyID { get; set; }
        public int EmpId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> TallyMapped { get; set; }
        public string LedgerName { get; set; }
        public Nullable<System.DateTime> LastSyncOn { get; set; }
    }
}
