//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserRole
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int UserRoleID { get; set; }
        public string RoleName { get; set; }
    }
}
